sudo: required
language: cpp
os:
  - linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - git
      - cmake      
compiler:
  - g++-8
before_install:
    - sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
    - git clone https://github.com/Microsoft/vcpkg.git vcpkg
    - cd vcpkg
    - chmod +x bootstrap-vcpkg.sh
    - ./bootstrap-vcpkg.sh
    - chmod +x vcpkg
    - ./vcpkg integrate install
    - ./vcpkg install glfw3
    - ./vcpkg install glad
    - ./vcpkg install glm
    - ./vcpkg install gtest
    - cd ..
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=/home/travis/build/mgerhold/Chip8Emulator/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-8 ..
  - make
  - ctest