sudo: required
language: cpp

branches:
    only:
        - master

os:
  - linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - git
      - cmake
      - doxygen
compiler:
  - g++-8
before_install:
    - sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
    - git clone https://github.com/Microsoft/vcpkg.git vcpkg
    - cd vcpkg
    - chmod +x bootstrap-vcpkg.sh
    - ./bootstrap-vcpkg.sh
    - chmod +x vcpkg
    - ./vcpkg integrate install
    - ./vcpkg install glfw3
    - ./vcpkg install glad
    - ./vcpkg install glm
    - ./vcpkg install nativefiledialog
    - ./vcpkg install gtest    
    - cd ..
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=/home/travis/build/mgerhold/Chip8Emulator/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 ..
  - make
  - ctest
  - cd ..
  - doxygen Doxyfile
  
deploy:
  provider: pages # defaults to branch "gh-pages", can otherwise be set with "target_branch: <name_of_branch>"
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master