sudo: required
language: cpp
os:
  - linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - glfw3-dev
      - glad-dev
      - glm-dev
      - cmake      
compiler:
  - g++-8
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 ..